# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'settings.ui'
##
## Created by: Qt User Interface Compiler version 6.2.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGraphicsView, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QWidget)

class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        if not SettingsWindow.objectName():
            SettingsWindow.setObjectName(u"SettingsWindow")
        SettingsWindow.resize(800, 620)
        SettingsWindow.setMinimumSize(QSize(800, 620))
        SettingsWindow.setMaximumSize(QSize(800, 620))
        SettingsWindow.setStyleSheet(u"QPushButton[piano_key=\"end\"] {\n"
"	background-color: gray; \n"
"	border-color: black;\n"
"	border-width: 1px;\n"
"	border-style: solid;\n"
"}\n"
"\n"
"QPushButton[piano_key=\"white\"] {\n"
"	background-color: white; \n"
"	border-color: black;\n"
"	border-width: 1px;\n"
"	border-style: solid;\n"
"	font-weight: 900;\n"
"}\n"
"\n"
"QPushButton[piano_key=\"white\"]:hover {\n"
"	background-color: rgb(71, 205, 255); \n"
"}\n"
"\n"
"QPushButton[piano_key=\"black\"] {\n"
"	background-color: black; \n"
"	border-color: black;\n"
"	border-width: 2px;\n"
"	border-style: solid;\n"
"	font-weight: 900;\n"
"	color: white;\n"
"}\n"
"\n"
"QPushButton[piano_key=\"black\"]:hover {\n"
"	background-color: rgb(71, 205, 255); \n"
"	border-color: rgb(71, 205, 255);\n"
"}\n"
"\n"
"QLabel[octave_indicator=\"true\"] {\n"
"	border-color: black;\n"
"	border-width: 2px;\n"
"	border-style: outset;\n"
"	border-bottom: none;\n"
"}\n"
"\n"
"QPushButton[note_enabled=\"false\"][piano_key=\"white\"]:!hover {\n"
"	background-color: rgb(255, 189,"
                        " 189);\n"
"}\n"
"\n"
"QPushButton[note_enabled=\"false\"][piano_key=\"black\"]:!hover {\n"
"	background-color: rgb(80, 0, 1);\n"
"	border-color: rgb(80, 0, 1);\n"
"}\n"
"\n"
"QPushButton[shecret_button=\"true\"] {\n"
"	background-color: rgba(105, 133, 255, 0)\n"
"}\n"
"")
        self.centralwidget = QWidget(SettingsWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.piano_left_end = QPushButton(self.centralwidget)
        self.piano_left_end.setObjectName(u"piano_left_end")
        self.piano_left_end.setEnabled(False)
        self.piano_left_end.setGeometry(QRect(30, 60, 19, 102))
        self.piano_d2 = QPushButton(self.centralwidget)
        self.piano_d2.setObjectName(u"piano_d2")
        self.piano_d2.setEnabled(True)
        self.piano_d2.setGeometry(QRect(49, 60, 20, 102))
        self.piano_d2.setProperty("note_enabled", True)
        self.piano_cS2 = QPushButton(self.centralwidget)
        self.piano_cS2.setObjectName(u"piano_cS2")
        self.piano_cS2.setGeometry(QRect(43, 60, 13, 63))
        self.piano_cS2.setProperty("note_enabled", True)
        self.piano_e2 = QPushButton(self.centralwidget)
        self.piano_e2.setObjectName(u"piano_e2")
        self.piano_e2.setGeometry(QRect(69, 60, 20, 102))
        self.piano_e2.setProperty("note_enabled", True)
        self.piano_f2 = QPushButton(self.centralwidget)
        self.piano_f2.setObjectName(u"piano_f2")
        self.piano_f2.setGeometry(QRect(89, 60, 20, 102))
        self.piano_f2.setProperty("note_enabled", True)
        self.piano_g2 = QPushButton(self.centralwidget)
        self.piano_g2.setObjectName(u"piano_g2")
        self.piano_g2.setGeometry(QRect(109, 60, 20, 102))
        self.piano_g2.setProperty("note_enabled", True)
        self.piano_a2 = QPushButton(self.centralwidget)
        self.piano_a2.setObjectName(u"piano_a2")
        self.piano_a2.setGeometry(QRect(129, 60, 20, 102))
        self.piano_a2.setProperty("note_enabled", True)
        self.piano_b2 = QPushButton(self.centralwidget)
        self.piano_b2.setObjectName(u"piano_b2")
        self.piano_b2.setGeometry(QRect(149, 60, 20, 102))
        self.piano_b2.setProperty("note_enabled", True)
        self.piano_c3 = QPushButton(self.centralwidget)
        self.piano_c3.setObjectName(u"piano_c3")
        self.piano_c3.setGeometry(QRect(169, 60, 20, 102))
        self.piano_c3.setProperty("note_enabled", True)
        self.piano_d3 = QPushButton(self.centralwidget)
        self.piano_d3.setObjectName(u"piano_d3")
        self.piano_d3.setGeometry(QRect(189, 60, 20, 102))
        self.piano_d3.setProperty("note_enabled", True)
        self.piano_e3 = QPushButton(self.centralwidget)
        self.piano_e3.setObjectName(u"piano_e3")
        self.piano_e3.setGeometry(QRect(209, 60, 20, 102))
        self.piano_e3.setProperty("note_enabled", True)
        self.piano_f3 = QPushButton(self.centralwidget)
        self.piano_f3.setObjectName(u"piano_f3")
        self.piano_f3.setGeometry(QRect(229, 60, 20, 102))
        self.piano_f3.setProperty("note_enabled", True)
        self.piano_g3 = QPushButton(self.centralwidget)
        self.piano_g3.setObjectName(u"piano_g3")
        self.piano_g3.setGeometry(QRect(249, 60, 20, 102))
        self.piano_g3.setProperty("note_enabled", True)
        self.piano_a3 = QPushButton(self.centralwidget)
        self.piano_a3.setObjectName(u"piano_a3")
        self.piano_a3.setGeometry(QRect(269, 60, 20, 102))
        self.piano_a3.setProperty("note_enabled", True)
        self.piano_b3 = QPushButton(self.centralwidget)
        self.piano_b3.setObjectName(u"piano_b3")
        self.piano_b3.setGeometry(QRect(289, 60, 20, 102))
        self.piano_b3.setProperty("note_enabled", True)
        self.piano_c4 = QPushButton(self.centralwidget)
        self.piano_c4.setObjectName(u"piano_c4")
        self.piano_c4.setGeometry(QRect(309, 60, 20, 102))
        self.piano_c4.setProperty("note_enabled", True)
        self.piano_d4 = QPushButton(self.centralwidget)
        self.piano_d4.setObjectName(u"piano_d4")
        self.piano_d4.setGeometry(QRect(329, 60, 20, 102))
        self.piano_d4.setProperty("note_enabled", True)
        self.piano_e4 = QPushButton(self.centralwidget)
        self.piano_e4.setObjectName(u"piano_e4")
        self.piano_e4.setGeometry(QRect(349, 60, 20, 102))
        self.piano_e4.setProperty("note_enabled", True)
        self.piano_f4 = QPushButton(self.centralwidget)
        self.piano_f4.setObjectName(u"piano_f4")
        self.piano_f4.setGeometry(QRect(369, 60, 20, 102))
        self.piano_f4.setProperty("note_enabled", True)
        self.piano_g4 = QPushButton(self.centralwidget)
        self.piano_g4.setObjectName(u"piano_g4")
        self.piano_g4.setGeometry(QRect(389, 60, 20, 102))
        self.piano_g4.setProperty("note_enabled", True)
        self.piano_a4 = QPushButton(self.centralwidget)
        self.piano_a4.setObjectName(u"piano_a4")
        self.piano_a4.setGeometry(QRect(409, 60, 20, 102))
        self.piano_a4.setProperty("note_enabled", True)
        self.piano_b4 = QPushButton(self.centralwidget)
        self.piano_b4.setObjectName(u"piano_b4")
        self.piano_b4.setGeometry(QRect(429, 60, 20, 102))
        self.piano_b4.setProperty("note_enabled", True)
        self.piano_c5 = QPushButton(self.centralwidget)
        self.piano_c5.setObjectName(u"piano_c5")
        self.piano_c5.setGeometry(QRect(449, 60, 20, 102))
        self.piano_c5.setProperty("note_enabled", True)
        self.piano_d5 = QPushButton(self.centralwidget)
        self.piano_d5.setObjectName(u"piano_d5")
        self.piano_d5.setGeometry(QRect(469, 60, 20, 102))
        self.piano_d5.setProperty("note_enabled", True)
        self.piano_e5 = QPushButton(self.centralwidget)
        self.piano_e5.setObjectName(u"piano_e5")
        self.piano_e5.setGeometry(QRect(489, 60, 20, 102))
        self.piano_e5.setProperty("note_enabled", True)
        self.piano_f5 = QPushButton(self.centralwidget)
        self.piano_f5.setObjectName(u"piano_f5")
        self.piano_f5.setGeometry(QRect(509, 60, 20, 102))
        self.piano_f5.setProperty("note_enabled", True)
        self.piano_g5 = QPushButton(self.centralwidget)
        self.piano_g5.setObjectName(u"piano_g5")
        self.piano_g5.setGeometry(QRect(529, 60, 20, 102))
        self.piano_g5.setProperty("note_enabled", True)
        self.piano_a5 = QPushButton(self.centralwidget)
        self.piano_a5.setObjectName(u"piano_a5")
        self.piano_a5.setGeometry(QRect(549, 60, 20, 102))
        self.piano_a5.setProperty("note_enabled", True)
        self.piano_b5 = QPushButton(self.centralwidget)
        self.piano_b5.setObjectName(u"piano_b5")
        self.piano_b5.setGeometry(QRect(569, 60, 20, 102))
        self.piano_b5.setProperty("note_enabled", True)
        self.piano_c6 = QPushButton(self.centralwidget)
        self.piano_c6.setObjectName(u"piano_c6")
        self.piano_c6.setGeometry(QRect(589, 60, 20, 102))
        self.piano_c6.setProperty("note_enabled", True)
        self.piano_d6 = QPushButton(self.centralwidget)
        self.piano_d6.setObjectName(u"piano_d6")
        self.piano_d6.setGeometry(QRect(609, 60, 20, 102))
        self.piano_d6.setProperty("note_enabled", True)
        self.piano_e6 = QPushButton(self.centralwidget)
        self.piano_e6.setObjectName(u"piano_e6")
        self.piano_e6.setGeometry(QRect(629, 60, 20, 102))
        self.piano_e6.setProperty("note_enabled", True)
        self.piano_f6 = QPushButton(self.centralwidget)
        self.piano_f6.setObjectName(u"piano_f6")
        self.piano_f6.setGeometry(QRect(649, 60, 20, 102))
        self.piano_f6.setProperty("note_enabled", True)
        self.piano_g6 = QPushButton(self.centralwidget)
        self.piano_g6.setObjectName(u"piano_g6")
        self.piano_g6.setGeometry(QRect(669, 60, 20, 102))
        self.piano_g6.setProperty("note_enabled", True)
        self.piano_a6 = QPushButton(self.centralwidget)
        self.piano_a6.setObjectName(u"piano_a6")
        self.piano_a6.setGeometry(QRect(689, 60, 20, 102))
        self.piano_a6.setProperty("note_enabled", True)
        self.piano_b6 = QPushButton(self.centralwidget)
        self.piano_b6.setObjectName(u"piano_b6")
        self.piano_b6.setGeometry(QRect(709, 60, 20, 102))
        self.piano_b6.setProperty("note_enabled", True)
        self.piano_right_end = QPushButton(self.centralwidget)
        self.piano_right_end.setObjectName(u"piano_right_end")
        self.piano_right_end.setEnabled(False)
        self.piano_right_end.setGeometry(QRect(749, 60, 20, 102))
        self.piano_dS2 = QPushButton(self.centralwidget)
        self.piano_dS2.setObjectName(u"piano_dS2")
        self.piano_dS2.setGeometry(QRect(63, 60, 13, 63))
        self.piano_dS2.setProperty("note_enabled", True)
        self.piano_fS2 = QPushButton(self.centralwidget)
        self.piano_fS2.setObjectName(u"piano_fS2")
        self.piano_fS2.setGeometry(QRect(103, 60, 13, 63))
        self.piano_fS2.setProperty("note_enabled", True)
        self.piano_gS2 = QPushButton(self.centralwidget)
        self.piano_gS2.setObjectName(u"piano_gS2")
        self.piano_gS2.setGeometry(QRect(123, 60, 13, 63))
        self.piano_gS2.setProperty("note_enabled", True)
        self.piano_aS2 = QPushButton(self.centralwidget)
        self.piano_aS2.setObjectName(u"piano_aS2")
        self.piano_aS2.setGeometry(QRect(143, 60, 13, 63))
        self.piano_aS2.setProperty("note_enabled", True)
        self.piano_fS3 = QPushButton(self.centralwidget)
        self.piano_fS3.setObjectName(u"piano_fS3")
        self.piano_fS3.setGeometry(QRect(243, 60, 13, 63))
        self.piano_fS3.setProperty("note_enabled", True)
        self.piano_cS3 = QPushButton(self.centralwidget)
        self.piano_cS3.setObjectName(u"piano_cS3")
        self.piano_cS3.setGeometry(QRect(183, 60, 13, 63))
        self.piano_cS3.setProperty("note_enabled", True)
        self.piano_aS3 = QPushButton(self.centralwidget)
        self.piano_aS3.setObjectName(u"piano_aS3")
        self.piano_aS3.setGeometry(QRect(283, 60, 13, 63))
        self.piano_aS3.setProperty("note_enabled", True)
        self.piano_dS3 = QPushButton(self.centralwidget)
        self.piano_dS3.setObjectName(u"piano_dS3")
        self.piano_dS3.setGeometry(QRect(203, 60, 13, 63))
        self.piano_dS3.setProperty("note_enabled", True)
        self.piano_gS3 = QPushButton(self.centralwidget)
        self.piano_gS3.setObjectName(u"piano_gS3")
        self.piano_gS3.setGeometry(QRect(263, 60, 13, 63))
        self.piano_gS3.setProperty("note_enabled", True)
        self.piano_fS4 = QPushButton(self.centralwidget)
        self.piano_fS4.setObjectName(u"piano_fS4")
        self.piano_fS4.setGeometry(QRect(383, 60, 13, 63))
        self.piano_fS4.setProperty("note_enabled", True)
        self.piano_cS4 = QPushButton(self.centralwidget)
        self.piano_cS4.setObjectName(u"piano_cS4")
        self.piano_cS4.setGeometry(QRect(323, 60, 13, 63))
        self.piano_cS4.setProperty("note_enabled", True)
        self.piano_aS4 = QPushButton(self.centralwidget)
        self.piano_aS4.setObjectName(u"piano_aS4")
        self.piano_aS4.setGeometry(QRect(423, 60, 13, 63))
        self.piano_aS4.setProperty("note_enabled", True)
        self.piano_dS4 = QPushButton(self.centralwidget)
        self.piano_dS4.setObjectName(u"piano_dS4")
        self.piano_dS4.setGeometry(QRect(343, 60, 13, 63))
        self.piano_dS4.setProperty("note_enabled", True)
        self.piano_gS4 = QPushButton(self.centralwidget)
        self.piano_gS4.setObjectName(u"piano_gS4")
        self.piano_gS4.setGeometry(QRect(403, 60, 13, 63))
        self.piano_gS4.setProperty("note_enabled", True)
        self.piano_fS5 = QPushButton(self.centralwidget)
        self.piano_fS5.setObjectName(u"piano_fS5")
        self.piano_fS5.setGeometry(QRect(523, 60, 13, 63))
        self.piano_fS5.setProperty("note_enabled", True)
        self.piano_cS5 = QPushButton(self.centralwidget)
        self.piano_cS5.setObjectName(u"piano_cS5")
        self.piano_cS5.setGeometry(QRect(463, 60, 13, 63))
        self.piano_cS5.setProperty("note_enabled", True)
        self.piano_aS5 = QPushButton(self.centralwidget)
        self.piano_aS5.setObjectName(u"piano_aS5")
        self.piano_aS5.setGeometry(QRect(563, 60, 13, 63))
        self.piano_aS5.setProperty("note_enabled", True)
        self.piano_dS5 = QPushButton(self.centralwidget)
        self.piano_dS5.setObjectName(u"piano_dS5")
        self.piano_dS5.setGeometry(QRect(483, 60, 13, 63))
        self.piano_dS5.setProperty("note_enabled", True)
        self.piano_gS5 = QPushButton(self.centralwidget)
        self.piano_gS5.setObjectName(u"piano_gS5")
        self.piano_gS5.setGeometry(QRect(543, 60, 13, 63))
        self.piano_gS5.setProperty("note_enabled", True)
        self.piano_fS6 = QPushButton(self.centralwidget)
        self.piano_fS6.setObjectName(u"piano_fS6")
        self.piano_fS6.setGeometry(QRect(663, 60, 13, 63))
        self.piano_fS6.setProperty("note_enabled", True)
        self.piano_cS6 = QPushButton(self.centralwidget)
        self.piano_cS6.setObjectName(u"piano_cS6")
        self.piano_cS6.setGeometry(QRect(603, 60, 13, 63))
        self.piano_cS6.setProperty("note_enabled", True)
        self.piano_aS6 = QPushButton(self.centralwidget)
        self.piano_aS6.setObjectName(u"piano_aS6")
        self.piano_aS6.setGeometry(QRect(703, 60, 13, 63))
        self.piano_aS6.setProperty("note_enabled", True)
        self.piano_dS6 = QPushButton(self.centralwidget)
        self.piano_dS6.setObjectName(u"piano_dS6")
        self.piano_dS6.setGeometry(QRect(623, 60, 13, 63))
        self.piano_dS6.setProperty("note_enabled", True)
        self.piano_gS6 = QPushButton(self.centralwidget)
        self.piano_gS6.setObjectName(u"piano_gS6")
        self.piano_gS6.setGeometry(QRect(683, 60, 13, 63))
        self.piano_gS6.setProperty("note_enabled", True)
        self.piano_c7 = QPushButton(self.centralwidget)
        self.piano_c7.setObjectName(u"piano_c7")
        self.piano_c7.setGeometry(QRect(729, 60, 20, 102))
        font = QFont()
        font.setBold(True)
        font.setItalic(False)
        self.piano_c7.setFont(font)
        self.piano_c7.setProperty("note_enabled", True)
        self.piano_cS7 = QPushButton(self.centralwidget)
        self.piano_cS7.setObjectName(u"piano_cS7")
        self.piano_cS7.setGeometry(QRect(742, 60, 13, 63))
        font1 = QFont()
        font1.setPointSize(5)
        font1.setBold(True)
        self.piano_cS7.setFont(font1)
        self.piano_cS7.setProperty("note_enabled", True)
        self.middle_c_arrow_label = QLabel(self.centralwidget)
        self.middle_c_arrow_label.setObjectName(u"middle_c_arrow_label")
        self.middle_c_arrow_label.setGeometry(QRect(314, 164, 16, 31))
        self.middle_c_arrow_label.setPixmap(QPixmap(u"assets/up_arrow.png"))
        self.middle_c_label = QLabel(self.centralwidget)
        self.middle_c_label.setObjectName(u"middle_c_label")
        self.middle_c_label.setGeometry(QRect(284, 192, 71, 16))
        self.octave_2_label = QLabel(self.centralwidget)
        self.octave_2_label.setObjectName(u"octave_2_label")
        self.octave_2_label.setGeometry(QRect(37, 31, 125, 20))
        self.octave_2_label.setProperty("octave_indicator", True)
        self.octave_3_label = QLabel(self.centralwidget)
        self.octave_3_label.setObjectName(u"octave_3_label")
        self.octave_3_label.setGeometry(QRect(177, 31, 125, 20))
        self.octave_3_label.setProperty("octave_indicator", True)
        self.octave_4_label = QLabel(self.centralwidget)
        self.octave_4_label.setObjectName(u"octave_4_label")
        self.octave_4_label.setGeometry(QRect(316, 31, 125, 20))
        self.octave_4_label.setProperty("octave_indicator", True)
        self.octave_5_label = QLabel(self.centralwidget)
        self.octave_5_label.setObjectName(u"octave_5_label")
        self.octave_5_label.setGeometry(QRect(457, 31, 125, 20))
        self.octave_5_label.setProperty("octave_indicator", True)
        self.octave_6_label = QLabel(self.centralwidget)
        self.octave_6_label.setObjectName(u"octave_6_label")
        self.octave_6_label.setGeometry(QRect(597, 31, 125, 20))
        self.octave_6_label.setProperty("octave_indicator", True)
        self.octave_7_label = QLabel(self.centralwidget)
        self.octave_7_label.setObjectName(u"octave_7_label")
        self.octave_7_label.setGeometry(QRect(735, 31, 28, 20))
        self.octave_7_label.setProperty("octave_indicator", True)
        self.octaves_label = QLabel(self.centralwidget)
        self.octaves_label.setObjectName(u"octaves_label")
        self.octaves_label.setGeometry(QRect(38, 10, 721, 20))
        font2 = QFont()
        font2.setBold(True)
        self.octaves_label.setFont(font2)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(7, 563, 781, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.disabled_color_ex_1 = QPushButton(self.centralwidget)
        self.disabled_color_ex_1.setObjectName(u"disabled_color_ex_1")
        self.disabled_color_ex_1.setEnabled(False)
        self.disabled_color_ex_1.setGeometry(QRect(30, 180, 31, 12))
        self.disabled_color_ex_1.setProperty("note_enabled", False)
        self.disabled_colors_label = QLabel(self.centralwidget)
        self.disabled_colors_label.setObjectName(u"disabled_colors_label")
        self.disabled_colors_label.setGeometry(QRect(68, 183, 71, 16))
        self.disabled_color_ex_2 = QPushButton(self.centralwidget)
        self.disabled_color_ex_2.setObjectName(u"disabled_color_ex_2")
        self.disabled_color_ex_2.setEnabled(False)
        self.disabled_color_ex_2.setGeometry(QRect(30, 191, 31, 12))
        self.disabled_color_ex_2.setAutoRepeatDelay(305)
        self.disabled_color_ex_2.setProperty("note_enabled", False)
        self.shecret_button = QPushButton(self.centralwidget)
        self.shecret_button.setObjectName(u"shecret_button")
        self.shecret_button.setGeometry(QRect(29, 179, 33, 26))
        self.shecret_button.setProperty("shecret_button", True)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(7, 209, 781, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.gf_major_checkbox = QCheckBox(self.centralwidget)
        self.gf_major_checkbox.setObjectName(u"gf_major_checkbox")
        self.gf_major_checkbox.setGeometry(QRect(478, 506, 16, 16))
        self.gf_major_display = QGraphicsView(self.centralwidget)
        self.gf_major_display.setObjectName(u"gf_major_display")
        self.gf_major_display.setGeometry(QRect(497, 474, 122, 78))
        self.gf_major_label = QLabel(self.centralwidget)
        self.gf_major_label.setObjectName(u"gf_major_label")
        self.gf_major_label.setGeometry(QRect(497, 452, 112, 16))
        self.fs_major_checkbox = QCheckBox(self.centralwidget)
        self.fs_major_checkbox.setObjectName(u"fs_major_checkbox")
        self.fs_major_checkbox.setGeometry(QRect(180, 398, 16, 16))
        self.fs_major_display = QGraphicsView(self.centralwidget)
        self.fs_major_display.setObjectName(u"fs_major_display")
        self.fs_major_display.setGeometry(QRect(199, 365, 122, 79))
        self.fs_major_label = QLabel(self.centralwidget)
        self.fs_major_label.setObjectName(u"fs_major_label")
        self.fs_major_label.setGeometry(QRect(199, 343, 104, 16))
        self.d_major_checkbox = QCheckBox(self.centralwidget)
        self.d_major_checkbox.setObjectName(u"d_major_checkbox")
        self.d_major_checkbox.setGeometry(QRect(329, 289, 16, 16))
        self.d_major_display = QGraphicsView(self.centralwidget)
        self.d_major_display.setObjectName(u"d_major_display")
        self.d_major_display.setGeometry(QRect(348, 257, 122, 78))
        self.d_major_label = QLabel(self.centralwidget)
        self.d_major_label.setObjectName(u"d_major_label")
        self.d_major_label.setGeometry(QRect(348, 235, 95, 16))
        self.f_major_checkbox = QCheckBox(self.centralwidget)
        self.f_major_checkbox.setObjectName(u"f_major_checkbox")
        self.f_major_checkbox.setGeometry(QRect(478, 398, 16, 16))
        self.f_major_label = QLabel(self.centralwidget)
        self.f_major_label.setObjectName(u"f_major_label")
        self.f_major_label.setGeometry(QRect(497, 343, 94, 16))
        self.f_major_display = QGraphicsView(self.centralwidget)
        self.f_major_display.setObjectName(u"f_major_display")
        self.f_major_display.setGeometry(QRect(497, 365, 122, 79))
        self.bf_major_checkbox = QCheckBox(self.centralwidget)
        self.bf_major_checkbox.setObjectName(u"bf_major_checkbox")
        self.bf_major_checkbox.setGeometry(QRect(627, 398, 16, 16))
        self.bf_major_label = QLabel(self.centralwidget)
        self.bf_major_label.setObjectName(u"bf_major_label")
        self.bf_major_label.setGeometry(QRect(646, 343, 104, 16))
        self.bf_major_display = QGraphicsView(self.centralwidget)
        self.bf_major_display.setObjectName(u"bf_major_display")
        self.bf_major_display.setGeometry(QRect(646, 365, 122, 79))
        self.b_major_label = QLabel(self.centralwidget)
        self.b_major_label.setObjectName(u"b_major_label")
        self.b_major_label.setGeometry(QRect(50, 343, 100, 16))
        self.b_major_checkbox = QCheckBox(self.centralwidget)
        self.b_major_checkbox.setObjectName(u"b_major_checkbox")
        self.b_major_checkbox.setGeometry(QRect(31, 398, 16, 16))
        self.b_major_display = QGraphicsView(self.centralwidget)
        self.b_major_display.setObjectName(u"b_major_display")
        self.b_major_display.setGeometry(QRect(50, 365, 122, 79))
        self.cf_major_label = QLabel(self.centralwidget)
        self.cf_major_label.setObjectName(u"cf_major_label")
        self.cf_major_label.setGeometry(QRect(646, 452, 114, 16))
        self.cf_major_checkbox = QCheckBox(self.centralwidget)
        self.cf_major_checkbox.setObjectName(u"cf_major_checkbox")
        self.cf_major_checkbox.setGeometry(QRect(627, 506, 16, 16))
        self.cf_major_display = QGraphicsView(self.centralwidget)
        self.cf_major_display.setObjectName(u"cf_major_display")
        self.cf_major_display.setGeometry(QRect(646, 474, 122, 78))
        self.af_major_checkbox = QCheckBox(self.centralwidget)
        self.af_major_checkbox.setObjectName(u"af_major_checkbox")
        self.af_major_checkbox.setGeometry(QRect(180, 506, 16, 16))
        self.af_major_label = QLabel(self.centralwidget)
        self.af_major_label.setObjectName(u"af_major_label")
        self.af_major_label.setGeometry(QRect(199, 452, 103, 16))
        self.af_major_display = QGraphicsView(self.centralwidget)
        self.af_major_display.setObjectName(u"af_major_display")
        self.af_major_display.setGeometry(QRect(199, 474, 122, 78))
        self.c_major_checkbox = QCheckBox(self.centralwidget)
        self.c_major_checkbox.setObjectName(u"c_major_checkbox")
        self.c_major_checkbox.setGeometry(QRect(31, 289, 16, 16))
        self.c_major_checkbox.setChecked(True)
        self.c_major_display = QGraphicsView(self.centralwidget)
        self.c_major_display.setObjectName(u"c_major_display")
        self.c_major_display.setGeometry(QRect(50, 257, 122, 78))
        self.c_major_label = QLabel(self.centralwidget)
        self.c_major_label.setObjectName(u"c_major_label")
        self.c_major_label.setGeometry(QRect(50, 235, 96, 16))
        self.df_major_checkbox = QCheckBox(self.centralwidget)
        self.df_major_checkbox.setObjectName(u"df_major_checkbox")
        self.df_major_checkbox.setGeometry(QRect(329, 506, 16, 16))
        self.df_major_label = QLabel(self.centralwidget)
        self.df_major_label.setObjectName(u"df_major_label")
        self.df_major_label.setGeometry(QRect(348, 452, 113, 16))
        self.df_major_display = QGraphicsView(self.centralwidget)
        self.df_major_display.setObjectName(u"df_major_display")
        self.df_major_display.setGeometry(QRect(348, 474, 122, 78))
        self.ef_major_display = QGraphicsView(self.centralwidget)
        self.ef_major_display.setObjectName(u"ef_major_display")
        self.ef_major_display.setGeometry(QRect(50, 474, 122, 78))
        self.ef_major_label = QLabel(self.centralwidget)
        self.ef_major_label.setObjectName(u"ef_major_label")
        self.ef_major_label.setGeometry(QRect(50, 452, 103, 16))
        self.ef_major_checkbox = QCheckBox(self.centralwidget)
        self.ef_major_checkbox.setObjectName(u"ef_major_checkbox")
        self.ef_major_checkbox.setGeometry(QRect(31, 506, 16, 16))
        self.cs_major_checkbox = QCheckBox(self.centralwidget)
        self.cs_major_checkbox.setObjectName(u"cs_major_checkbox")
        self.cs_major_checkbox.setGeometry(QRect(329, 398, 16, 16))
        self.cs_major_display = QGraphicsView(self.centralwidget)
        self.cs_major_display.setObjectName(u"cs_major_display")
        self.cs_major_display.setGeometry(QRect(348, 365, 122, 79))
        self.cs_major_label = QLabel(self.centralwidget)
        self.cs_major_label.setObjectName(u"cs_major_label")
        self.cs_major_label.setGeometry(QRect(348, 343, 106, 16))
        self.g_major_checkbox = QCheckBox(self.centralwidget)
        self.g_major_checkbox.setObjectName(u"g_major_checkbox")
        self.g_major_checkbox.setGeometry(QRect(180, 289, 16, 16))
        self.g_major_display = QGraphicsView(self.centralwidget)
        self.g_major_display.setObjectName(u"g_major_display")
        self.g_major_display.setGeometry(QRect(199, 257, 122, 78))
        self.g_major_label = QLabel(self.centralwidget)
        self.g_major_label.setObjectName(u"g_major_label")
        self.g_major_label.setGeometry(QRect(199, 235, 94, 16))
        self.a_major_checkbox = QCheckBox(self.centralwidget)
        self.a_major_checkbox.setObjectName(u"a_major_checkbox")
        self.a_major_checkbox.setGeometry(QRect(478, 289, 16, 16))
        self.a_major_label = QLabel(self.centralwidget)
        self.a_major_label.setObjectName(u"a_major_label")
        self.a_major_label.setGeometry(QRect(497, 235, 99, 16))
        self.a_major_display = QGraphicsView(self.centralwidget)
        self.a_major_display.setObjectName(u"a_major_display")
        self.a_major_display.setGeometry(QRect(497, 257, 122, 78))
        self.e_major_checkbox = QCheckBox(self.centralwidget)
        self.e_major_checkbox.setObjectName(u"e_major_checkbox")
        self.e_major_checkbox.setGeometry(QRect(627, 289, 16, 16))
        self.e_major_label = QLabel(self.centralwidget)
        self.e_major_label.setObjectName(u"e_major_label")
        self.e_major_label.setGeometry(QRect(646, 235, 99, 16))
        self.e_major_display = QGraphicsView(self.centralwidget)
        self.e_major_display.setObjectName(u"e_major_display")
        self.e_major_display.setGeometry(QRect(646, 257, 122, 78))
        self.save_button = QPushButton(self.centralwidget)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setGeometry(QRect(612, 583, 75, 24))
        self.quit_button = QPushButton(self.centralwidget)
        self.quit_button.setObjectName(u"quit_button")
        self.quit_button.setGeometry(QRect(693, 583, 75, 24))
        self.help_button = QPushButton(self.centralwidget)
        self.help_button.setObjectName(u"help_button")
        self.help_button.setGeometry(QRect(531, 583, 75, 24))
        self.enable_chord_picking_checkbox = QCheckBox(self.centralwidget)
        self.enable_chord_picking_checkbox.setObjectName(u"enable_chord_picking_checkbox")
        self.enable_chord_picking_checkbox.setGeometry(QRect(32, 585, 136, 20))
        self.clef_selection = QComboBox(self.centralwidget)
        self.clef_selection.addItem("")
        self.clef_selection.addItem("")
        self.clef_selection.addItem("")
        self.clef_selection.setObjectName(u"clef_selection")
        self.clef_selection.setGeometry(QRect(240, 584, 71, 22))
        font3 = QFont()
        font3.setPointSize(9)
        self.clef_selection.setFont(font3)
        self.clef_label = QLabel(self.centralwidget)
        self.clef_label.setObjectName(u"clef_label")
        self.clef_label.setGeometry(QRect(210, 587, 24, 16))
        self.clef_label.setFont(font3)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(180, 581, 16, 29))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        SettingsWindow.setCentralWidget(self.centralwidget)
        self.save_button.raise_()
        self.quit_button.raise_()
        self.help_button.raise_()
        self.enable_chord_picking_checkbox.raise_()
        self.clef_selection.raise_()
        self.clef_label.raise_()
        self.line_2.raise_()
        self.gf_major_checkbox.raise_()
        self.gf_major_display.raise_()
        self.gf_major_label.raise_()
        self.fs_major_checkbox.raise_()
        self.fs_major_display.raise_()
        self.fs_major_label.raise_()
        self.d_major_checkbox.raise_()
        self.d_major_display.raise_()
        self.d_major_label.raise_()
        self.f_major_checkbox.raise_()
        self.f_major_label.raise_()
        self.f_major_display.raise_()
        self.bf_major_checkbox.raise_()
        self.bf_major_label.raise_()
        self.bf_major_display.raise_()
        self.b_major_label.raise_()
        self.b_major_checkbox.raise_()
        self.b_major_display.raise_()
        self.cf_major_label.raise_()
        self.cf_major_checkbox.raise_()
        self.cf_major_display.raise_()
        self.af_major_checkbox.raise_()
        self.af_major_label.raise_()
        self.af_major_display.raise_()
        self.c_major_checkbox.raise_()
        self.c_major_display.raise_()
        self.c_major_label.raise_()
        self.df_major_checkbox.raise_()
        self.df_major_label.raise_()
        self.df_major_display.raise_()
        self.ef_major_display.raise_()
        self.ef_major_label.raise_()
        self.ef_major_checkbox.raise_()
        self.cs_major_checkbox.raise_()
        self.cs_major_display.raise_()
        self.cs_major_label.raise_()
        self.g_major_checkbox.raise_()
        self.g_major_display.raise_()
        self.g_major_label.raise_()
        self.a_major_checkbox.raise_()
        self.a_major_label.raise_()
        self.a_major_display.raise_()
        self.e_major_checkbox.raise_()
        self.e_major_label.raise_()
        self.e_major_display.raise_()
        self.piano_left_end.raise_()
        self.piano_d2.raise_()
        self.piano_f2.raise_()
        self.piano_g2.raise_()
        self.piano_a2.raise_()
        self.piano_b2.raise_()
        self.piano_c3.raise_()
        self.piano_d3.raise_()
        self.piano_e3.raise_()
        self.piano_f3.raise_()
        self.piano_g3.raise_()
        self.piano_a3.raise_()
        self.piano_b3.raise_()
        self.piano_c4.raise_()
        self.piano_d4.raise_()
        self.piano_e4.raise_()
        self.piano_f4.raise_()
        self.piano_g4.raise_()
        self.piano_a4.raise_()
        self.piano_b4.raise_()
        self.piano_c5.raise_()
        self.piano_d5.raise_()
        self.piano_e5.raise_()
        self.piano_f5.raise_()
        self.piano_g5.raise_()
        self.piano_a5.raise_()
        self.piano_b5.raise_()
        self.piano_c6.raise_()
        self.piano_d6.raise_()
        self.piano_e6.raise_()
        self.piano_f6.raise_()
        self.piano_g6.raise_()
        self.piano_a6.raise_()
        self.piano_b6.raise_()
        self.piano_right_end.raise_()
        self.piano_c7.raise_()
        self.piano_e2.raise_()
        self.middle_c_arrow_label.raise_()
        self.middle_c_label.raise_()
        self.octave_2_label.raise_()
        self.octave_3_label.raise_()
        self.octave_4_label.raise_()
        self.octave_5_label.raise_()
        self.octave_6_label.raise_()
        self.octave_7_label.raise_()
        self.octaves_label.raise_()
        self.line.raise_()
        self.disabled_color_ex_1.raise_()
        self.disabled_colors_label.raise_()
        self.disabled_color_ex_2.raise_()
        self.shecret_button.raise_()
        self.line_3.raise_()
        self.piano_aS3.raise_()
        self.piano_aS4.raise_()
        self.piano_aS2.raise_()
        self.piano_aS5.raise_()
        self.piano_aS6.raise_()
        self.piano_cS6.raise_()
        self.piano_cS3.raise_()
        self.piano_cS4.raise_()
        self.piano_cS5.raise_()
        self.piano_cS7.raise_()
        self.piano_cS2.raise_()
        self.piano_dS5.raise_()
        self.piano_dS6.raise_()
        self.piano_dS2.raise_()
        self.piano_dS4.raise_()
        self.piano_dS3.raise_()
        self.piano_fS5.raise_()
        self.piano_fS4.raise_()
        self.piano_fS6.raise_()
        self.piano_fS2.raise_()
        self.piano_fS3.raise_()
        self.piano_gS2.raise_()
        self.piano_gS6.raise_()
        self.piano_gS4.raise_()
        self.piano_gS5.raise_()
        self.piano_gS3.raise_()

        self.retranslateUi(SettingsWindow)

        QMetaObject.connectSlotsByName(SettingsWindow)
    # setupUi

    def retranslateUi(self, SettingsWindow):
        SettingsWindow.setWindowTitle(QCoreApplication.translate("SettingsWindow", u"Settings", None))
#if QT_CONFIG(statustip)
        SettingsWindow.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        SettingsWindow.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.piano_left_end.setText("")
        self.piano_left_end.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"end", None))
        self.piano_d2.setText("")
        self.piano_d2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_cS2.setText("")
        self.piano_cS2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_e2.setText("")
        self.piano_e2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_f2.setText("")
        self.piano_f2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_g2.setText("")
        self.piano_g2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_a2.setText("")
        self.piano_a2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_b2.setText("")
        self.piano_b2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_c3.setText("")
        self.piano_c3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_d3.setText("")
        self.piano_d3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_e3.setText("")
        self.piano_e3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_f3.setText("")
        self.piano_f3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_g3.setText("")
        self.piano_g3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_a3.setText("")
        self.piano_a3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_b3.setText("")
        self.piano_b3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_c4.setText("")
        self.piano_c4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_d4.setText("")
        self.piano_d4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_e4.setText("")
        self.piano_e4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_f4.setText("")
        self.piano_f4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_g4.setText("")
        self.piano_g4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_a4.setText("")
        self.piano_a4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_b4.setText("")
        self.piano_b4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_c5.setText("")
        self.piano_c5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_d5.setText("")
        self.piano_d5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_e5.setText("")
        self.piano_e5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_f5.setText("")
        self.piano_f5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_g5.setText("")
        self.piano_g5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_a5.setText("")
        self.piano_a5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_b5.setText("")
        self.piano_b5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_c6.setText("")
        self.piano_c6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_d6.setText("")
        self.piano_d6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_e6.setText("")
        self.piano_e6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_f6.setText("")
        self.piano_f6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_g6.setText("")
        self.piano_g6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_a6.setText("")
        self.piano_a6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_b6.setText("")
        self.piano_b6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_right_end.setText("")
        self.piano_right_end.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"end", None))
        self.piano_dS2.setText("")
        self.piano_dS2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_fS2.setText("")
        self.piano_fS2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_gS2.setText("")
        self.piano_gS2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_aS2.setText("")
        self.piano_aS2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_fS3.setText("")
        self.piano_fS3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_cS3.setText("")
        self.piano_cS3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_aS3.setText("")
        self.piano_aS3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_dS3.setText("")
        self.piano_dS3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_gS3.setText("")
        self.piano_gS3.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_fS4.setText("")
        self.piano_fS4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_cS4.setText("")
        self.piano_cS4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_aS4.setText("")
        self.piano_aS4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_dS4.setText("")
        self.piano_dS4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_gS4.setText("")
        self.piano_gS4.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_fS5.setText("")
        self.piano_fS5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_cS5.setText("")
        self.piano_cS5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_aS5.setText("")
        self.piano_aS5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_dS5.setText("")
        self.piano_dS5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_gS5.setText("")
        self.piano_gS5.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_fS6.setText("")
        self.piano_fS6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_cS6.setText("")
        self.piano_cS6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_aS6.setText("")
        self.piano_aS6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_dS6.setText("")
        self.piano_dS6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_gS6.setText("")
        self.piano_gS6.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.piano_c7.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.piano_cS7.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.middle_c_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">Middle C</p></body></html>", None))
        self.octave_2_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">2</p></body></html>", None))
        self.octave_3_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">3</p></body></html>", None))
        self.octave_4_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">4</p></body></html>", None))
        self.octave_5_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">5</p></body></html>", None))
        self.octave_6_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">6</p></body></html>", None))
        self.octave_7_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">7</p></body></html>", None))
        self.octaves_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">Octaves</p></body></html>", None))
        self.disabled_color_ex_1.setText("")
        self.disabled_color_ex_1.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"white", None))
        self.disabled_colors_label.setText(QCoreApplication.translate("SettingsWindow", u"= Disabled", None))
        self.disabled_color_ex_2.setText("")
        self.disabled_color_ex_2.setProperty("piano_key", QCoreApplication.translate("SettingsWindow", u"black", None))
        self.shecret_button.setText("")
        self.gf_major_checkbox.setText("")
        self.gf_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">G\u266dMajor (E\u266dMinor)</p></body></html>", None))
        self.fs_major_checkbox.setText("")
        self.fs_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">F\u266f Major (D\u266f Minor)</p></body></html>", None))
        self.d_major_checkbox.setText("")
        self.d_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">D Major (B Minor)</p></body></html>", None))
        self.f_major_checkbox.setText("")
        self.f_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">F Major (D Minor)</p></body></html>", None))
        self.bf_major_checkbox.setText("")
        self.bf_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">B\u266dMajor (G Minor)</p></body></html>", None))
        self.b_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">B Major (G\u266f Minor)</p></body></html>", None))
        self.b_major_checkbox.setText("")
        self.cf_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">C\u266dMajor (A\u266dMinor)</p></body></html>", None))
        self.cf_major_checkbox.setText("")
        self.af_major_checkbox.setText("")
        self.af_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">A\u266dMajor (F Minor)</p></body></html>", None))
        self.c_major_checkbox.setText("")
        self.c_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">C Major (A Minor)</p></body></html>", None))
        self.df_major_checkbox.setText("")
        self.df_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">D\u266dMajor (B\u266dMinor)</p></body></html>", None))
        self.ef_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">E\u266dMajor (C Minor)</p></body></html>", None))
        self.ef_major_checkbox.setText("")
        self.cs_major_checkbox.setText("")
        self.cs_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">C\u266f Major (A\u266f Minor)</p></body></html>", None))
        self.g_major_checkbox.setText("")
        self.g_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">G Major (E Minor)</p></body></html>", None))
        self.a_major_checkbox.setText("")
        self.a_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">A Major (F\u266f Minor)</p></body></html>", None))
        self.e_major_checkbox.setText("")
        self.e_major_label.setText(QCoreApplication.translate("SettingsWindow", u"<html><head/><body><p align=\"center\">E Major (C\u266f Minor)</p></body></html>", None))
        self.save_button.setText(QCoreApplication.translate("SettingsWindow", u"Save", None))
        self.quit_button.setText(QCoreApplication.translate("SettingsWindow", u"Quit", None))
        self.help_button.setText(QCoreApplication.translate("SettingsWindow", u"Help", None))
#if QT_CONFIG(statustip)
        self.enable_chord_picking_checkbox.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.enable_chord_picking_checkbox.setText(QCoreApplication.translate("SettingsWindow", u"Enable Chord Picking", None))
        self.clef_selection.setItemText(0, QCoreApplication.translate("SettingsWindow", u"Treble", None))
        self.clef_selection.setItemText(1, QCoreApplication.translate("SettingsWindow", u"Bass", None))
        self.clef_selection.setItemText(2, QCoreApplication.translate("SettingsWindow", u"Random", None))

        self.clef_label.setText(QCoreApplication.translate("SettingsWindow", u"Clef:", None))
    # retranslateUi

